---

samba_realm: domain.alt
samba_domain: "{{ samba_realm.split('.')|list|first }}"
samba_admin_pass: peebieY4
samba_network: 192.168.122.0/24
samba_dns_forward: 192.168.122.1
samba_dns_backend: SAMBA_INTERNAL
samba_master_address: "{{ hostvars[groups['samba_master_dc'][0]].ansible_host }}"
samba_master_hostname: "{{ hostvars[groups['samba_master_dc'][0]].inventory_hostname_short }}"

extra_apt_repos:
  - name: localsssd
    description: SSSD 1.16.3 (locally built)
    entry: "http://{{ samba_dns_forward }}:8000/sssd p8 x86_64"
