
- name: install OpenLDAP utilities
  package: name=openldap-clients state=present
  become: true

- name: prevent OpenLDAP tools from fiddling with reverse DNS
  lineinfile:
    dest: /etc/openldap/ldap.conf
    line: 'sasl_nocanon yes'
    state: present
    create: yes
  become: true

- name: install SASL GSSAPI plugin
  package: name=libsasl2-plugin-gssapi state=present
  become: true

- name: install iconv tool
  package: name=iconv state=present
  become: true

- include: extra_apt_repo.yml
  with_items: "{{ extra_apt_repos|default([]) }}"

- name: check if SSSD is installed
  command: rpm -ql sssd
  register: sssd_status_out
  failed_when: false

- name: upgrade SSSD
  package: name=sssd state=present update_cache=yes
  when: sssd_status_out.rc == 0
  become: true

- set_fact:
    samba_master_fqdn: "{{ samba_master_hostname }}.{{ samba_realm }}"

- include: testuser.yml

- include: OUs.yml
  with_items: "{{ test_ous }}"

- include: move2ou.yml
  with_items: "{{ groups['samba_clients'] }}"
  vars:
    dest_OU: "{{ test_ous[0].name }}"

- include: gpoobj.yml
  with_items: "{{ test_gpos }}"
