---

- name: configure samba DC as a primary DNS
  win_dns_client:
    adapter_names: "{{ ansible_interfaces[0].connection_name }}"
    ipv4_addresses:
      - "{{ samba_master_address }}"
      - "{{ samba_dns_forward }}"

- name: join to the domain
  win_domain_membership:
    dns_domain_name: "{{ samba_realm }}"
    state: domain
    domain_admin_user: "administrator@{{ samba_realm }}"
    domain_admin_password: "{{ samba_admin_pass }}"
  register: domain_state

- name: enable remote desktop service
  win_command: >
    reg add "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Terminal Server"
    /v fDenyTSConnections /t REG_DWORD /d 0 /f

- name: enable rdesktop connections in windows firewall
  win_command: >
    netsh firewall set service RemoteDesktop enable

- name: reboot
  win_reboot:
     #-
  when: domain_state.reboot_required|bool
