---

- name: configure samba DC as a primary DNS
  win_dns_client:
    adapter_names: "{{ ansible_interfaces[0].connection_name }}"
    ipv4_addresses:
      - "{{ samba_master_address }}"
      - "{{ samba_dns_forward }}"

- name: join to the domain
  win_domain_membership:
    dns_domain_name: "{{ samba_realm }}"
    state: domain
    domain_admin_user: "administrator@{{ samba_realm }}"
    domain_admin_password: "{{ samba_admin_pass }}"
  register: domain_state

- name: reboot
  win_reboot:
     #-
  when: domain_state.reboot_required|bool
